# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CocoaHeads' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaHeads
  pod 'Alamofire', '~> 4.5'
  pod 'Moya', '~> 10.0'
  pod 'UIAlertController+Blocks'
  pod 'LoremIpsum'
end
